name: Deploy Network Monitor to Azure ACI

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: "pynetmon-rg"
  IMAGE_NAME: "deflauthuman/network-monitor:latest"
  CONTAINER_NAME: "python-monitor-container"
  LOCATION: "malaysiawest"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ env.IMAGE_NAME }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Instances
      run: |
        az container create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.CONTAINER_NAME }} \
          --image ${{ env.IMAGE_NAME }} \
          --cpu 1 \
          --memory 1 \
          --location ${{ env.LOCATION }} \
          --os-type Linux \
          --azure-file-volume-account-name pynetmonstorage999 \
          --azure-file-volume-account-key ${{ secrets.AZURE_STORAGE_KEY }} \
          --azure-file-volume-share-name csvreports \
          --azure-file-volume-mount-path /app/reports \
          --environment-variables PYTHONUNBUFFERED=1 \
          --restart-policy Always

    # --restart-policy Always: Để Cloud tự động phục hồi nếu script Network bị lỗi nhỏ rồi văng
